# Generated by Django 3.2.4 on 2021-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_help', '0002_remove_doctor_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='comments',
            field=models.CharField(default='', max_length=250),
        ),
    ]
