# Generated by Django 3.2.4 on 2021-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_help', '0003_doctor_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='comment_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
