# Generated by Django 3.2.4 on 2021-09-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_help', '0004_doctor_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='comment_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='comments',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=250)),
                ('comment_name', models.CharField(default='', max_length=250)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_help.doctor')),
            ],
        ),
    ]
