# Generated by Django 3.2.4 on 2021-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_help', '0005_auto_20210911_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='username',
            field=models.CharField(default='', max_length=250),
        ),
    ]
